# Generated by Django 4.2.1 on 2024-08-06 14:01

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=common.models.CustomPhoneNumberField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_number',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
    ]
