# Generated by Django 4.2.1 on 2024-08-04 22:52

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
    ]
