# Generated by Django 4.2.1 on 2024-08-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_by'),
        ('leads', '0003_alter_lead_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='address_line',
            new_name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_from_site',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='opportunity_amount',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='street',
        ),
        migrations.AddField(
            model_name='lead',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tasks',
            field=models.ManyToManyField(related_name='lead_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
