# Generated by Django 4.2.1 on 2024-08-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_lead'),
        ('teams', '0003_alter_teams_created_by'),
        ('leads', '0004_rename_address_line_lead_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('closed', 'Closed')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='lead_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='lead_teams', to='teams.teams'),
        ),
    ]
