# Generated by Django 4.2.1 on 2024-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_lead'),
        ('teams', '0003_alter_teams_created_by'),
        ('leads', '0004_rename_address_line_lead_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='lead_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='lead_teams', to='teams.teams'),
        ),
    ]
