# Generated by Django 4.2.1 on 2024-08-06 14:04

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='phone',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
    ]
