# Generated by Django 4.2.1 on 2024-08-06 14:04

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_attachments_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_phone',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=common.models.CustomPhoneNumberField(max_length=15, null=True, unique=True),
        ),
    ]
