# Generated by Django 4.2.1 on 2024-08-06 13:59

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=common.models.CustomPhoneNumberField(blank=True, max_length=15, null=True),
        ),
    ]
