# Generated by Django 4.2.1 on 2024-08-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='previous_billing_country',
            new_name='previous_residency_country',
        ),
    ]
