# Generated by Django 4.2.1 on 2024-08-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_modify_phone_req'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_rentersintake_commercialintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIntake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('VIN', models.CharField(max_length=255, verbose_name='VIN')),
                ('model_year', models.IntegerField(verbose_name='Car Model Year')),
                ('make', models.CharField(blank=True, max_length=255, null=True, verbose_name='Car Make')),
                ('model', models.CharField(max_length=255, verbose_name='Car Model')),
                ('liability_coverage', models.BooleanField(verbose_name='Liability Coverage')),
                ('collision_coverage', models.BooleanField(verbose_name='Collision Coverage')),
                ('comprehensive_coverage', models.BooleanField(verbose_name='Comprehensive Coverage')),
                ('personal_injury_protection_pip', models.BooleanField(verbose_name='Personal Injury Protection (PIP)')),
                ('medical_payments', models.BooleanField(verbose_name='Medical Payments')),
                ('uninsured_underinsured_motorist_coverage', models.BooleanField(verbose_name='Uninsured/Underinsured Motorist Coverage')),
                ('rental_reimbursement_coverage', models.BooleanField(verbose_name='Rental Reimbursement Coverage')),
                ('roadside_assistance', models.BooleanField(verbose_name='Roadside Assistance')),
                ('gap_insurance', models.BooleanField(verbose_name='Gap Insurance')),
                ('custom_parts_and_equipment_coverage', models.BooleanField(verbose_name='Custom Parts and Equipment Coverage')),
                ('accident_forgiveness', models.BooleanField(verbose_name='Accident Forgiveness')),
                ('new_car_replacement', models.BooleanField(verbose_name='New Car Replacement')),
                ('loss_of_use', models.BooleanField(verbose_name='Loss of Use')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_intake_org', to='common.org')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='current_insurance_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='driver_liscence_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='married',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='rated_driver_or_excluded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='violations',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_intake_driver', to='accounts.account')),
                ('auto_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_auto_driver', to='accounts.autointake')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
