# Generated by Django 4.2.1 on 2024-08-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0002_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentersInsuranceIntake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('secondary_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_owner_date_of_birth', models.DateField(blank=True, null=True)),
                ('secondary_owner_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('limit_of_coverage_desired', models.BooleanField(blank=True, null=True)),
                ('has_dogs', models.BooleanField()),
                ('number_of_dogs', models.IntegerField(blank=True, null=True)),
                ('dog_breeds', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='opportunity.opportunity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
