# Generated by Django 4.2.1 on 2024-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_modify_phone_req'),
        ('teams', '0003_alter_teams_created_by'),
        ('tasks', '0003_task_lead'),
        ('opportunity', '0003_remove_opportunity_account_remove_opportunity_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='account_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='opportunity_assigned_to', to='common.profile'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Needs Quote', 'Needs Quote'), ('Quoting in Progress', 'Quoting in Progress'), ('Quoted', 'Quoted'), ('Quote Accepted', 'Quote Accepted'), ('Quote Rejected', 'Quote Rejected')], max_length=64, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='opportunity_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='oppurtunity_teams', to='teams.teams'),
        ),
    ]
