# Generated by Django 4.2.1 on 2024-08-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_rentersinsuranceintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentersInsuranceIntake',
        ),
    ]
