# Generated by Django 4.2.1 on 2024-08-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_delete_rentersinsuranceintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='probability',
        ),
    ]
