# Generated by Django 4.2.1 on 2024-08-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_address_line_lead_address_line_1_and_more'),
        ('tasks', '0002_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_tasks', to='leads.lead'),
        ),
    ]
