# Generated by Django 4.2.1 on 2024-08-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_modify_phone_req'),
        ('lender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_org', to='common.org'),
        ),
    ]
